<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\**" />
    <Compile Remove="Views\Home\**" />
    <Content Remove="Controllers\**" />
    <Content Remove="Views\Home\**" />
    <EmbeddedResource Remove="Controllers\**" />
    <EmbeddedResource Remove="Views\Home\**" />
    <None Remove="Controllers\**" />
    <None Remove="Views\Home\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Customer\ViewModels\" />  
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.12" />
    <PackageReference Include="Stripe.net" Version="50.4.0" />
  </ItemGroup>

</Project>
